In [1]:
import pandas as pd

file_path = r"C:\Users\Yekam\Downloads\Gen_AI Dataset.xlsx"

xls = pd.ExcelFile(file_path)
print(xls.sheet_names)

['Train-Set', 'Test-Set']

In [2]:
train_df = pd.read_excel(file_path, sheet_name=0)
test_df = pd.read_excel(file_path, sheet_name=1)

train_df.head()

,Query,Assessment_url
0,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
1,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
2,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
3,I am hiring for Java developers who can also c...,https://www.shl.com/solutions/products/product...
4,I am hiring for Java developers who can also c...,https://www.shl.com/products/product-catalog/v...

In [3]:
# Group all relevant URLs per query
train_grouped = train_df.groupby("Query")["Assessment_url"].apply(list).reset_index()

train_grouped.head()

,Query,Assessment_url
0,Based on the JD below recommend me assessment ...,[https://www.shl.com/solutions/products/produc...
1,"Content Writer required, expert in English and...",[https://www.shl.com/products/product-catalog/...
2,Find me 1 hour long assesment for the below jo...,[https://www.shl.com/solutions/products/produc...
3,I am hiring for Java developers who can also c...,[https://www.shl.com/solutions/products/produc...
4,I am looking for a COO for my company in China...,[https://www.shl.com/products/product-catalog/...

In [4]:
len(train_grouped)

10

In [6]:
import requests

url = "https://www.shl.com/solutions/products/product-catalog/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

200

In [7]:
import requests
from bs4 import BeautifulSoup

base_url = "https://www.shl.com"
catalog_url = "https://www.shl.com/solutions/products/product-catalog/"

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(catalog_url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

links = []

for a in soup.find_all("a", href=True):
    href = a["href"]
    if "/products/product-catalog/" in href:
        if "job-solutions" not in href.lower():  # Ignore pre-packaged job solutions
            full_link = href if href.startswith("http") else base_url + href
            links.append(full_link)

# Remove duplicates
links = list(set(links))

print("Total links found:", len(links))
links[:10]

Total links found: 31

['https://www.shl.com/products/product-catalog/view/bank-administrative-assistant-short-form/',
 'https://www.shl.com/products/product-catalog/view/apprentice-8-0-job-focused-assessment-4261/',
 'https://www.shl.com/products/product-catalog/?start=372&type=1',
 'https://www.shl.com/products/product-catalog/view/bilingual-spanish-reservation-agent-solution/',
 'https://www.shl.com/products/product-catalog/view/administrative-professional-short-form/',
 'https://www.shl.com/products/product-catalog/view/bank-collections-agent-short-form/',
 'https://www.shl.com/products/product-catalog/?start=132&type=2',
 'https://www.shl.com/products/product-catalog/view/account-manager-solution/',
 'https://www.shl.com/products/product-catalog/view/bank-operations-supervisor-short-form/',
 'https://www.shl.com/products/product-catalog/view/global-skills-development-report/']

In [8]:
import requests
from bs4 import BeautifulSoup
import time

base_url = "https://www.shl.com"
headers = {"User-Agent": "Mozilla/5.0"}

all_links = set()

start = 0
step = 12   # pagination step (usually 12 per page)

while True:
    url = f"https://www.shl.com/products/product-catalog/?start={start}&type=1"
    print("Scraping:", url)

    response = requests.get(url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")

    page_links = []

    for a in soup.find_all("a", href=True):
        href = a["href"]
        if "/products/product-catalog/view/" in href:
            full_link = base_url + href
            page_links.append(full_link)

    if not page_links:
        break

    for link in page_links:
        all_links.add(link)

    start += step
    time.sleep(1)

print("Total Individual Assessments Found:", len(all_links))

Scraping: https://www.shl.com/products/product-catalog/?start=0&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=12&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=24&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=36&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=48&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=60&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=72&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=84&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=96&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=108&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=120&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=132&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=144&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=156&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=168&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=180&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=192&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=204&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=216&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=228&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=240&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=252&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=264&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=276&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=288&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=300&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=312&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=324&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=336&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=348&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=360&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=372&type=1
Scraping: https://www.shl.com/products/product-catalog/?start=384&type=1
Total Individual Assessments Found: 389

In [9]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time

headers = {"User-Agent": "Mozilla/5.0"}

catalog_data = []

for i, link in enumerate(all_links):
    print(f"Scraping {i+1}/{len(all_links)}")

    try:
        response = requests.get(link, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")

        name = soup.find("h1").text.strip() if soup.find("h1") else ""

        description_tag = soup.find("div", class_="field--name-field-description")
        description = description_tag.text.strip() if description_tag else ""

        # Extract metadata section text
        page_text = soup.get_text().lower()

        duration = ""
        if "min" in page_text:
            duration = "Mentioned in page"

        remote_support = "yes" if "remote" in page_text else "no"
        adaptive_support = "yes" if "adaptive" in page_text or "irt" in page_text else "no"

        test_type = ""
        if "knowledge" in page_text:
            test_type = "K"
        elif "personality" in page_text:
            test_type = "P"

        catalog_data.append({
            "name": name,
            "url": link,
            "description": description,
            "duration": duration,
            "remote_support": remote_support,
            "adaptive_support": adaptive_support,
            "test_type": test_type
        })

        time.sleep(0.5)

    except Exception as e:
        print("Error:", e)

catalog_df = pd.DataFrame(catalog_data)
catalog_df.to_csv("catalog.csv", index=False)

print("Catalog saved. Total rows:", len(catalog_df))

Scraping 1/389
Scraping 2/389
Scraping 3/389
Scraping 4/389
Scraping 5/389
Scraping 6/389
Scraping 7/389
Scraping 8/389
Scraping 9/389
Scraping 10/389
Scraping 11/389
Scraping 12/389
Scraping 13/389
Scraping 14/389
Scraping 15/389
Scraping 16/389
Scraping 17/389
Scraping 18/389
Scraping 19/389
Scraping 20/389
Scraping 21/389
Scraping 22/389
Scraping 23/389
Scraping 24/389
Scraping 25/389
Scraping 26/389
Scraping 27/389
Scraping 28/389
Scraping 29/389
Scraping 30/389
Scraping 31/389
Scraping 32/389
Scraping 33/389
Scraping 34/389
Scraping 35/389
Scraping 36/389
Scraping 37/389
Scraping 38/389
Scraping 39/389
Scraping 40/389
Scraping 41/389
Scraping 42/389
Scraping 43/389
Scraping 44/389
Scraping 45/389
Scraping 46/389
Scraping 47/389
Scraping 48/389
Scraping 49/389
Scraping 50/389
Scraping 51/389
Scraping 52/389
Scraping 53/389
Scraping 54/389
Scraping 55/389
Scraping 56/389
Scraping 57/389
Scraping 58/389
Scraping 59/389
Scraping 60/389
Scraping 61/389
Scraping 62/389
Scraping 63/389
Scraping 64/389
Scraping 65/389
Scraping 66/389
Scraping 67/389
Scraping 68/389
Scraping 69/389
Scraping 70/389
Scraping 71/389
Scraping 72/389
Scraping 73/389
Scraping 74/389
Scraping 75/389
Scraping 76/389
Scraping 77/389
Scraping 78/389
Scraping 79/389
Scraping 80/389
Scraping 81/389
Scraping 82/389
Scraping 83/389
Scraping 84/389
Scraping 85/389
Scraping 86/389
Scraping 87/389
Scraping 88/389
Scraping 89/389
Scraping 90/389
Scraping 91/389
Scraping 92/389
Scraping 93/389
Scraping 94/389
Scraping 95/389
Scraping 96/389
Scraping 97/389
Scraping 98/389
Scraping 99/389
Scraping 100/389
Scraping 101/389
Scraping 102/389
Scraping 103/389
Scraping 104/389
Scraping 105/389
Scraping 106/389
Scraping 107/389
Scraping 108/389
Scraping 109/389
Scraping 110/389
Scraping 111/389
Scraping 112/389
Scraping 113/389
Scraping 114/389
Scraping 115/389
Scraping 116/389
Scraping 117/389
Scraping 118/389
Scraping 119/389
Scraping 120/389
Scraping 121/389
Scraping 122/389
Scraping 123/389
Scraping 124/389
Scraping 125/389
Scraping 126/389
Scraping 127/389
Scraping 128/389
Scraping 129/389
Scraping 130/389
Scraping 131/389
Scraping 132/389
Scraping 133/389
Scraping 134/389
Scraping 135/389
Scraping 136/389
Scraping 137/389
Scraping 138/389
Scraping 139/389
Scraping 140/389
Scraping 141/389
Scraping 142/389
Scraping 143/389
Scraping 144/389
Scraping 145/389
Scraping 146/389
Scraping 147/389
Scraping 148/389
Scraping 149/389
Scraping 150/389
Scraping 151/389
Scraping 152/389
Scraping 153/389
Scraping 154/389
Scraping 155/389
Scraping 156/389
Scraping 157/389
Scraping 158/389
Scraping 159/389
Scraping 160/389
Scraping 161/389
Scraping 162/389
Scraping 163/389
Scraping 164/389
Scraping 165/389
Scraping 166/389
Scraping 167/389
Scraping 168/389
Scraping 169/389
Scraping 170/389
Scraping 171/389
Scraping 172/389
Scraping 173/389
Scraping 174/389
Scraping 175/389
Scraping 176/389
Scraping 177/389
Scraping 178/389
Scraping 179/389
Scraping 180/389
Scraping 181/389
Scraping 182/389
Scraping 183/389
Scraping 184/389
Scraping 185/389
Scraping 186/389
Scraping 187/389
Scraping 188/389
Scraping 189/389
Scraping 190/389
Scraping 191/389
Scraping 192/389
Scraping 193/389
Scraping 194/389
Scraping 195/389
Scraping 196/389
Scraping 197/389
Scraping 198/389
Scraping 199/389
Scraping 200/389
Scraping 201/389
Scraping 202/389
Scraping 203/389
Scraping 204/389
Scraping 205/389
Scraping 206/389
Scraping 207/389
Scraping 208/389
Scraping 209/389
Scraping 210/389
Scraping 211/389
Scraping 212/389
Scraping 213/389
Scraping 214/389
Scraping 215/389
Scraping 216/389
Scraping 217/389
Scraping 218/389
Scraping 219/389
Scraping 220/389
Scraping 221/389
Scraping 222/389
Scraping 223/389
Scraping 224/389
Scraping 225/389
Scraping 226/389
Scraping 227/389
Scraping 228/389
Scraping 229/389
Scraping 230/389
Scraping 231/389
Scraping 232/389
Scraping 233/389
Scraping 234/389
Scraping 235/389
Scraping 236/389
Scraping 237/389
Scraping 238/389
Scraping 239/389
Scraping 240/389
Scraping 241/389
Scraping 242/389
Scraping 243/389
Scraping 244/389
Scraping 245/389
Scraping 246/389
Scraping 247/389
Scraping 248/389
Scraping 249/389
Scraping 250/389
Scraping 251/389
Scraping 252/389
Scraping 253/389
Scraping 254/389
Scraping 255/389
Scraping 256/389
Scraping 257/389
Scraping 258/389
Scraping 259/389
Scraping 260/389
Scraping 261/389
Scraping 262/389
Scraping 263/389
Scraping 264/389
Scraping 265/389
Scraping 266/389
Scraping 267/389
Scraping 268/389
Scraping 269/389
Scraping 270/389
Scraping 271/389
Scraping 272/389
Scraping 273/389
Scraping 274/389
Scraping 275/389
Scraping 276/389
Scraping 277/389
Scraping 278/389
Scraping 279/389
Scraping 280/389
Scraping 281/389
Scraping 282/389
Scraping 283/389
Scraping 284/389
Scraping 285/389
Scraping 286/389
Scraping 287/389
Scraping 288/389
Scraping 289/389
Scraping 290/389
Scraping 291/389
Scraping 292/389
Scraping 293/389
Scraping 294/389
Scraping 295/389
Scraping 296/389
Scraping 297/389
Scraping 298/389
Scraping 299/389
Scraping 300/389
Scraping 301/389
Scraping 302/389
Scraping 303/389
Scraping 304/389
Scraping 305/389
Scraping 306/389
Scraping 307/389
Scraping 308/389
Scraping 309/389
Scraping 310/389
Scraping 311/389
Scraping 312/389
Scraping 313/389
Scraping 314/389
Scraping 315/389
Scraping 316/389
Scraping 317/389
Scraping 318/389
Scraping 319/389
Scraping 320/389
Scraping 321/389
Scraping 322/389
Scraping 323/389
Scraping 324/389
Scraping 325/389
Scraping 326/389
Scraping 327/389
Scraping 328/389
Scraping 329/389
Scraping 330/389
Scraping 331/389
Scraping 332/389
Scraping 333/389
Scraping 334/389
Scraping 335/389
Scraping 336/389
Scraping 337/389
Scraping 338/389
Scraping 339/389
Scraping 340/389
Scraping 341/389
Scraping 342/389
Scraping 343/389
Scraping 344/389
Scraping 345/389
Scraping 346/389
Scraping 347/389
Scraping 348/389
Scraping 349/389
Scraping 350/389
Scraping 351/389
Scraping 352/389
Scraping 353/389
Scraping 354/389
Scraping 355/389
Scraping 356/389
Scraping 357/389
Scraping 358/389
Scraping 359/389
Scraping 360/389
Scraping 361/389
Scraping 362/389
Scraping 363/389
Scraping 364/389
Scraping 365/389
Scraping 366/389
Scraping 367/389
Scraping 368/389
Scraping 369/389
Scraping 370/389
Scraping 371/389
Scraping 372/389
Scraping 373/389
Scraping 374/389
Scraping 375/389
Scraping 376/389
Scraping 377/389
Scraping 378/389
Scraping 379/389
Scraping 380/389
Scraping 381/389
Scraping 382/389
Scraping 383/389
Scraping 384/389
Scraping 385/389
Scraping 386/389
Scraping 387/389
Scraping 388/389
Scraping 389/389
Catalog saved. Total rows: 389

In [1]:
import os
os.listdir()

['.bash_history',
 '.cache',
 '.conda',
 '.continuum',
 '.copilot',
 '.cursor',
 '.dotnet',
 '.git-credentials',
 '.git-for-windows-updater',
 '.gitconfig',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdk',
 '.jupyter',
 '.keras',
 '.kube',
 '.lesshst',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.redhat',
 '.ssh',
 '.th-client',
 '.VirtualBox',
 '.vscode',
 '.zenmap',
 'AppData',
 'Application Data',
 'catalog.csv',
 'Contacts - Copy',
 'Cookies',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'Links',
 'Local Settings',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{5fd0042d-96ca-11f0-854c-cd7814935c69}.TM.blf',
 'NTUSER.DAT{5fd0042d-96ca-11f0-854c-cd7814935c69}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{5fd0042d-96ca-11f0-854c-cd7814935c69}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'PrintHood',
 'Recent',
 'Saved Games',
 'Searches',
 'SendTo',
 'SHL_RAG_Assignment.ipynb',
 'smart-bookmark-app',
 'Start Menu',
 'Templates',
 'Videos',
 'VirtualBox VMs']

In [7]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (1.6.0)
Requirement already satisfied: numpy>=1.19.5 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.14.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install faiss-cpu

Requirement already satisfied: faiss-cpu in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (1.13.2)
Requirement already satisfied: numpy<3.0,>=1.25.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from faiss-cpu) (24.1)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
!pip install sentence-transformers faiss-cpu scikit-learn

Collecting sentence-transformers
  Using cached sentence_transformers-5.2.3-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: faiss-cpu in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (1.13.2)
Requirement already satisfied: scikit-learn in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (1.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (5.2.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.5.0)
Requirement already satisfied: torch>=1.11.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (2.10.0)
Requirement already satisfied: numpy in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (2.0.2)
Requirement already satisfied: scipy in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (1.14.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.12.2)
Requirement already satisfied: tqdm in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sentence-transformers) (4.66.5)
Requirement already satisfied: packaging>=20.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (24.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2024.9.11)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.24.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2026.2.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.3.2)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.28.1)
Requirement already satisfied: typer in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (0.24.1)
Requirement already satisfied: anyio in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (4.9.0)
Requirement already satisfied: certifi in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (2024.8.30)
Requirement already satisfied: httpcore==1.* in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (0.16.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.4)
Requirement already satisfied: setuptools in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.11.0->sentence-transformers) (75.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: sniffio>=1.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub>=0.20.0->sentence-transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.5)
Requirement already satisfied: click>=8.2.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from typer->huggingface-hub>=0.20.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (2.18.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.20.0->sentence-transformers) (0.1.2)
Using cached sentence_transformers-5.2.3-py3-none-any.whl (494 kB)
Installing collected packages: sentence-transformers
Successfully installed sentence-transformers-5.2.3

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Load catalog
catalog_df = pd.read_csv("catalog.csv")

catalog_df = catalog_df[catalog_df["name"].notna()]
catalog_df["description"] = catalog_df["description"].fillna("")

# Combine text fields
catalog_df["combined_text"] = (
    catalog_df["name"] + " " +
    catalog_df["description"] + " " +
    catalog_df["test_type"]
)

# Build TF-IDF
vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = vectorizer.fit_transform(catalog_df["combined_text"])

print("TF-IDF matrix shape:", tfidf_matrix.shape)

TF-IDF matrix shape: (389, 463)

In [13]:
def retrieve(query, top_k=10):
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    
    top_indices = similarities.argsort()[-top_k:][::-1]
    
    return catalog_df.iloc[top_indices][["name", "url", "test_type"]]

retrieve("Java developer who collaborates with business teams")

,name,url,test_type
105,Informatica (Developer) (New),https://www.shl.com/products/product-catalog/v...,K
14,Java 8 (New),https://www.shl.com/products/product-catalog/v...,K
218,Business Communications,https://www.shl.com/products/product-catalog/v...,K
87,Java Platform Enterprise Edition 7 (Java EE 7),https://www.shl.com/products/product-catalog/v...,K
110,Software Business Analysis,https://www.shl.com/products/product-catalog/v...,K
73,Java Frameworks (New),https://www.shl.com/products/product-catalog/v...,K
286,Business Communication (adaptive),https://www.shl.com/products/product-catalog/v...,K
74,Java Web Services (New),https://www.shl.com/products/product-catalog/v...,K
234,SAP BW (Business Warehouse) (New),https://www.shl.com/products/product-catalog/v...,K
60,SAP Business Objects WebI (New),https://www.shl.com/products/product-catalog/v...,K

In [19]:
def retrieve_raw(query, top_k=25):
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-top_k:][::-1]
    return catalog_df.iloc[top_indices].copy()

In [20]:
def balanced_recommend(query, final_k=10):
    results = retrieve_raw(query, top_k=25)
    
    # Detect soft-skill keywords
    soft_keywords = ["collaborate", "stakeholder", "communication", "team", "leadership"]
    is_soft = any(word in query.lower() for word in soft_keywords)
    
    if not is_soft:
        return results.head(final_k)[["name", "url", "test_type"]]
    
    # Separate by type
    k_tests = results[results["test_type"] == "K"]
    p_tests = results[results["test_type"] == "P"]
    
    # Ensure at least 3 P tests if available
    selected = pd.concat([
        k_tests.head(final_k - 3),
        p_tests.head(3)
    ])
    
    return selected.head(final_k)[["name", "url", "test_type"]]

In [21]:
balanced_recommend("Java developer who collaborates with business teams")

,name,url,test_type
105,Informatica (Developer) (New),https://www.shl.com/products/product-catalog/v...,K
14,Java 8 (New),https://www.shl.com/products/product-catalog/v...,K
218,Business Communications,https://www.shl.com/products/product-catalog/v...,K
87,Java Platform Enterprise Edition 7 (Java EE 7),https://www.shl.com/products/product-catalog/v...,K
110,Software Business Analysis,https://www.shl.com/products/product-catalog/v...,K
73,Java Frameworks (New),https://www.shl.com/products/product-catalog/v...,K
286,Business Communication (adaptive),https://www.shl.com/products/product-catalog/v...,K

In [22]:
catalog_df["test_type"].value_counts()

test_type
K    389
Name: count, dtype: int64

In [23]:
def classify_test_type(name):
    name_lower = name.lower()
    
    personality_keywords = [
        "personality", "behavior", "behaviour",
        "leadership", "motivation", "workplace",
        "opq", "situational judgement", "judgment",
        "teamwork", "collaboration"
    ]
    
    cognitive_keywords = [
        "ability", "reasoning", "cognitive",
        "numerical", "verbal", "logical",
        "deductive", "inductive"
    ]
    
    for word in personality_keywords:
        if word in name_lower:
            return "P"
    
    for word in cognitive_keywords:
        if word in name_lower:
            return "C"
    
    return "K"

catalog_df["test_type"] = catalog_df["name"].apply(classify_test_type)

catalog_df["test_type"].value_counts()

test_type
K    343
P     32
C     14
Name: count, dtype: int64

In [24]:
balanced_recommend("Java developer who collaborates with business teams")

,name,url,test_type
105,Informatica (Developer) (New),https://www.shl.com/products/product-catalog/v...,K
14,Java 8 (New),https://www.shl.com/products/product-catalog/v...,K
218,Business Communications,https://www.shl.com/products/product-catalog/v...,K
87,Java Platform Enterprise Edition 7 (Java EE 7),https://www.shl.com/products/product-catalog/v...,K
110,Software Business Analysis,https://www.shl.com/products/product-catalog/v...,K
73,Java Frameworks (New),https://www.shl.com/products/product-catalog/v...,K
286,Business Communication (adaptive),https://www.shl.com/products/product-catalog/v...,K
24,OPQ Team Types and Leadership Styles Report,https://www.shl.com/products/product-catalog/v...,P

In [26]:
import pandas as pd

file_path = r"C:\Users\Yekam\Downloads\Gen_AI Dataset.xlsx"

train_df = pd.read_excel(file_path, sheet_name=0)

# Group URLs per query
train_grouped = train_df.groupby("Query")["Assessment_url"].apply(list).reset_index()

print("Total unique queries:", len(train_grouped))
train_grouped.head()

Total unique queries: 10

,Query,Assessment_url
0,Based on the JD below recommend me assessment ...,[https://www.shl.com/solutions/products/produc...
1,"Content Writer required, expert in English and...",[https://www.shl.com/products/product-catalog/...
2,Find me 1 hour long assesment for the below jo...,[https://www.shl.com/solutions/products/produc...
3,I am hiring for Java developers who can also c...,[https://www.shl.com/solutions/products/produc...
4,I am looking for a COO for my company in China...,[https://www.shl.com/products/product-catalog/...

In [27]:
def recommend_urls(query, top_k=10):
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-top_k:][::-1]
    return catalog_df.iloc[top_indices]["url"].tolist()

def recall_at_10(query, true_urls):
    predicted = recommend_urls(query, top_k=10)
    relevant_found = len(set(predicted) & set(true_urls))
    return relevant_found / len(true_urls)

recalls = []

for _, row in train_grouped.iterrows():
    query = row["Query"]
    true_urls = row["Assessment_url"]
    r = recall_at_10(query, true_urls)
    recalls.append(r)

mean_recall = sum(recalls) / len(recalls)

print("Mean Recall@10:", mean_recall)

Mean Recall@10: 0.02

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return text

catalog_df["clean_name"] = catalog_df["name"].fillna("").apply(preprocess)

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1,2),
    max_features=3000
)

tfidf_matrix = vectorizer.fit_transform(catalog_df["clean_name"])

print("TF-IDF built successfully")

TF-IDF built successfully

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import re

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return text

catalog_df["clean_name"] = catalog_df["name"].fillna("").apply(preprocess)

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1,2),
    max_features=3000
)

tfidf_matrix = vectorizer.fit_transform(catalog_df["clean_name"])

print("TF-IDF built successfully")

TF-IDF built successfully

In [29]:
def recommend_urls(query, top_k=10):
    query = preprocess(query)
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-top_k:][::-1]
    return catalog_df.iloc[top_indices]["url"].tolist()

In [30]:
recalls = []

for _, row in train_grouped.iterrows():
    query = row["Query"]
    true_urls = row["Assessment_url"]
    r = recall_at_10(query, true_urls)
    recalls.append(r)

mean_recall = sum(recalls) / len(recalls)
print("Improved Mean Recall@10:", mean_recall)

Improved Mean Recall@10: 0.02

In [31]:
def normalize_url(url):
    url = url.lower()
    url = url.replace("https://www.shl.com", "")
    url = url.replace("/solutions", "")
    url = url.rstrip("/")
    return url

In [32]:
def recall_at_10(query, true_urls):
    predicted = recommend_urls(query, top_k=10)
    
    predicted_norm = set([normalize_url(u) for u in predicted])
    true_norm = set([normalize_url(u) for u in true_urls])
    
    relevant_found = len(predicted_norm & true_norm)
    return relevant_found / len(true_norm)

In [38]:
def recommend_urls(query, top_k=10):
    query = preprocess(query)
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-top_k:][::-1]
    return catalog_df.iloc[top_indices]["url"].tolist()

In [39]:
recalls = []

for _, row in train_grouped.iterrows():
    query = row["Query"]
    true_urls = row["Assessment_url"]
    r = recall_at_10(query, true_urls)
    recalls.append(r)

mean_recall = sum(recalls) / len(recalls)
print("Title-based Mean Recall@10:", mean_recall)

Title-based Mean Recall@10: 0.15555555555555556

In [40]:
# Normalize catalog URLs
catalog_urls_norm = set(catalog_df["url"].apply(normalize_url))

missing_count = 0
total_count = 0

for _, row in train_grouped.iterrows():
    true_urls = row["Assessment_url"]
    for u in true_urls:
        total_count += 1
        if normalize_url(u) not in catalog_urls_norm:
            missing_count += 1

print("Total train URLs:", total_count)
print("Missing from catalog:", missing_count)
print("Missing percentage:", missing_count / total_count)

Total train URLs: 65
Missing from catalog: 11
Missing percentage: 0.16923076923076924

In [42]:
import re

def preprocess(text):
    text = text.lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return text

def extract_slug(url):
    slug = url.split("/")[-2] if url.endswith("/") else url.split("/")[-1]
    slug = slug.replace("-", " ")
    return slug

catalog_df["slug_text"] = catalog_df["url"].apply(extract_slug)

catalog_df["enhanced_text"] = (
    catalog_df["name"].fillna("") + " " +
    catalog_df["slug_text"].fillna("")
)

catalog_df["enhanced_text"] = catalog_df["enhanced_text"].apply(preprocess)

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

vectorizer = TfidfVectorizer(
    stop_words="english",
    ngram_range=(1,2),
    max_features=5000
)

tfidf_matrix = vectorizer.fit_transform(catalog_df["enhanced_text"])

In [44]:
def recommend_urls(query, top_k=10):
    query = preprocess(query)
    query_vec = vectorizer.transform([query])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-top_k:][::-1]
    return catalog_df.iloc[top_indices]["url"].tolist()

In [46]:
def detect_domains(query):
    query = query.lower()
    
    technical = any(word in query for word in 
                    ["java", "python", "sql", "developer", "software", "analyst"])
    
    behavioral = any(word in query for word in 
                     ["team", "collaborate", "leadership", "stakeholder", "communication"])
    
    cognitive = any(word in query for word in 
                    ["cognitive", "reasoning", "aptitude", "analytical", "problem solving"])
    
    return technical, behavioral, cognitive

In [48]:
def recommend_urls(query, top_k=10):
    query_clean = preprocess(query)
    query_vec = vectorizer.transform([query_clean])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    
    tech, behav, cog = detect_domains(query)
    
    scores = similarities.copy()
    
    for i in range(len(scores)):
        ttype = catalog_df.iloc[i]["test_type"]
        
        if tech and ttype == "K":
            scores[i] += 0.1
        if behav and ttype == "P":
            scores[i] += 0.1
        if cog and ttype == "C":
            scores[i] += 0.1
    
    top_indices = scores.argsort()[-top_k:][::-1]
    return catalog_df.iloc[top_indices]["url"].tolist()

In [50]:
recalls = []

for _, row in train_grouped.iterrows():
    query = row["Query"]
    true_urls = row["Assessment_url"]
    r = recall_at_10(query, true_urls)
    recalls.append(r)

mean_recall = sum(recalls) / len(recalls)
print("Slug-enhanced Mean Recall@10:", mean_recall)

Slug-enhanced Mean Recall@10: 0.15555555555555556

In [56]:
query = train_grouped.iloc[0]["Query"]

# Raw similarities
query_clean = preprocess(query)

query_vec = vectorizer.transform([query_clean])
similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()

# Boosted scores
tech, behav, cog = detect_domains(query)
boosted = similarities.copy()

for i in range(len(boosted)):
    ttype = catalog_df.iloc[i]["test_type"]
    if tech and ttype == "K":
        boosted[i] += 0.1
    if behav and ttype == "P":
        boosted[i] += 0.1
    if cog and ttype == "C":
        boosted[i] += 0.1

print("Top 5 before boost:")
print(similarities.argsort()[-5:][::-1])

print("Top 5 after boost:")
print(boosted.argsort()[-5:][::-1])

Top 5 before boost:
[387 362 173  21  75]
Top 5 after boost:
[ 58 387 362 173  78]

In [57]:
def retrieve_top_20(query):
    query_clean = preprocess(query)
    query_vec = vectorizer.transform([query_clean])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-20:][::-1]
    return catalog_df.iloc[top_indices]

In [58]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (0.8.6)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (2.30.0)
Requirement already satisfied: google-api-python-client in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (2.190.0)
Requirement already satisfied: google-auth>=2.15.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (2.49.0.dev0)
Requirement already satisfied: protobuf in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (5.29.1)
Requirement already satisfied: pydantic in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (2.12.5)
Requirement already satisfied: tqdm in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (4.66.5)
Requirement already satisfied: typing-extensions in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.27.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.3 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-core->google-generativeai) (1.72.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-core->google-generativeai) (2.32.3)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.78.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-auth>=2.15.0->google-generativeai) (44.0.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (1.26.20)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.20.0->google-api-core->google-generativeai) (2024.8.30)
Requirement already satisfied: cffi>=1.12 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (1.17.1)
Requirement already satisfied: pycparser in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from cffi>=1.12->cryptography>=38.0.3->google-auth>=2.15.0->google-generativeai) (2.22)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.2)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-python-client->google-generativeai) (0.31.2)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-python-client->google-generativeai) (0.3.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: pyparsing<4,>=3.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic->google-generativeai) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: colorama in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from tqdm->google-generativeai) (0.4.6)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [62]:
!pip install --upgrade typing_extensions

Requirement already satisfied: typing_extensions in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (4.15.0)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [63]:
!pip install --upgrade pydantic

Requirement already satisfied: pydantic in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (2.12.5)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\yekam\appdata\local\programs\python\python312\lib\site-packages (from pydantic) (0.4.2)

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
API_KEY = "AIzaSyAAcO87V7LBCkyl8Lm8d1i3Iy5gqHLsj_g"

In [8]:
import requests

url = "https://generativelanguage.googleapis.com/v1/models"
params = {"key": API_KEY}

response = requests.get(url, params=params)

print("Status Code:", response.status_code)
print(response.text)

Status Code: 200
{
  "models": [
    {
      "name": "models/gemini-2.5-flash",
      "version": "001",
      "displayName": "Gemini 2.5 Flash",
      "description": "Stable version of Gemini 2.5 Flash, our mid-size multimodal model that supports up to 1 million tokens, released in June of 2025.",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 65536,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 64,
      "maxTemperature": 2,
      "thinking": true
    },
    {
      "name": "models/gemini-2.5-pro",
      "version": "2.5",
      "displayName": "Gemini 2.5 Pro",
      "description": "Stable release (June 17th, 2025) of Gemini 2.5 Pro",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 65536,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 64,
      "maxTemperature": 2,
      "thinking": true
    },
    {
      "name": "models/gemini-2.0-flash",
      "version": "2.0",
      "displayName": "Gemini 2.0 Flash",
      "description": "Gemini 2.0 Flash",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 8192,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 40,
      "maxTemperature": 2
    },
    {
      "name": "models/gemini-2.0-flash-001",
      "version": "2.0",
      "displayName": "Gemini 2.0 Flash 001",
      "description": "Stable version of Gemini 2.0 Flash, our fast and versatile multimodal model for scaling across diverse tasks, released in January of 2025.",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 8192,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 40,
      "maxTemperature": 2
    },
    {
      "name": "models/gemini-2.0-flash-lite-001",
      "version": "2.0",
      "displayName": "Gemini 2.0 Flash-Lite 001",
      "description": "Stable version of Gemini 2.0 Flash-Lite",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 8192,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 40,
      "maxTemperature": 2
    },
    {
      "name": "models/gemini-2.0-flash-lite",
      "version": "2.0",
      "displayName": "Gemini 2.0 Flash-Lite",
      "description": "Gemini 2.0 Flash-Lite",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 8192,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 40,
      "maxTemperature": 2
    },
    {
      "name": "models/gemini-2.5-flash-lite",
      "version": "001",
      "displayName": "Gemini 2.5 Flash-Lite",
      "description": "Stable version of Gemini 2.5 Flash-Lite, released in July of 2025",
      "inputTokenLimit": 1048576,
      "outputTokenLimit": 65536,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens",
        "createCachedContent",
        "batchGenerateContent"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 64,
      "maxTemperature": 2,
      "thinking": true
    }
  ]
}

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import re

# Load catalog again
catalog_df = pd.read_csv("catalog.csv")

def preprocess(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return text

catalog_df["clean_text"] = (
    catalog_df["name"].fillna("") + " " +
    catalog_df["url"].fillna("")
).apply(preprocess)

vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
tfidf_matrix = vectorizer.fit_transform(catalog_df["clean_text"])

def retrieve_top_20(query):
    query_clean = preprocess(query)
    query_vec = vectorizer.transform([query_clean])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-20:][::-1]
    return catalog_df.iloc[top_indices]

In [12]:
API_KEY = "AIzaSyAAcO87V7LBCkyl8Lm8d1i3Iy5gqHLsj_g"

In [17]:
import requests

def rerank_with_gemini(query):
    candidates = retrieve_top_20(query)

    prompt = f"""
You are an expert SHL assessment recommendation system.

Job Description:
{query}

Here are candidate assessments:
"""

    for _, row in candidates.iterrows():
        prompt += f"""
Name: {row['name']}
Test Type: {row['test_type']}
URL: {row['url']}
"""

    prompt += """
Select the best 5 to 10 most relevant assessments.
Ensure balanced mix if technical and behavioral skills are mentioned.
Return ONLY a Python list of URLs.
"""

    url = "https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash-lite:generateContent"

    headers = {
        "Content-Type": "application/json"
    }

    params = {
        "key": API_KEY
    }

    payload = {
        "contents": [
            {
                "parts": [{"text": prompt}]
            }
        ]
    }

    response = requests.post(url, headers=headers, params=params, json=payload)

    return response.json()

In [18]:
rerank_with_gemini("Java developer who collaborates with business teams")

{'candidates': [{'content': {'parts': [{'text': 'Here are the recommended SHL assessments for a "Java developer who collaborates with business teams":\n\n```python\n[\n  "https://www.shl.com/products/product-catalog/view/java-8-new/",\n  "https://www.shl.com/products/product-catalog/view/java-frameworks-new/",\n  "https://www.shl.com/products/product-catalog/view/java-web-services-new/",\n  "https://www.shl.com/products/product-catalog/view/java-design-patterns-new/",\n  "https://www.shl.com/products/product-catalog/view/core-java-advanced-level-new/",\n  "https://www.shl.com/products/product-catalog/view/software-business-analysis/",\n  "https://www.shl.com/products/product-catalog/view/business-communications/",\n  "https://www.shl.com/products/product-catalog/view/business-communication-adaptive/"\n]\n```'}],
    'role': 'model'},
   'finishReason': 'STOP',
   'index': 0}],
 'usageMetadata': {'promptTokenCount': 949,
  'candidatesTokenCount': 242,
  'totalTokenCount': 1191,
  'promptTokensDetails': [{'modality': 'TEXT', 'tokenCount': 949}]},
 'modelVersion': 'gemini-2.5-flash-lite',
 'responseId': 'c0ukadX9A6jljuMPm_iDyA8'}

In [19]:
import ast
import re

def extract_urls_from_response(response_json):
    try:
        text = response_json["candidates"][0]["content"]["parts"][0]["text"]
        
        # Extract Python list inside backticks
        match = re.search(r"\[(.*?)\]", text, re.DOTALL)
        if match:
            url_list_str = "[" + match.group(1) + "]"
            urls = ast.literal_eval(url_list_str)
            return urls
        else:
            return []
    except:
        return []

In [20]:
def recommend_with_llm(query):
    response = rerank_with_gemini(query)
    urls = extract_urls_from_response(response)
    return urls

In [22]:
recommend_with_llm("Java developer who collaborates with business teams")

['https://www.shl.com/products/product-catalog/view/java-8-new/',
 'https://www.shl.com/products/product-catalog/view/java-platform-enterprise-edition-7-java-ee-7/',
 'https://www.shl.com/products/product-catalog/view/java-frameworks-new/',
 'https://www.shl.com/products/product-catalog/view/java-web-services-new/',
 'https://www.shl.com/products/product-catalog/view/java-design-patterns-new/',
 'https://www.shl.com/products/product-catalog/view/core-java-advanced-level-new/',
 'https://www.shl.com/products/product-catalog/view/software-business-analysis/',
 'https://www.shl.com/products/product-catalog/view/business-communications/',
 'https://www.shl.com/products/product-catalog/view/business-communication-adaptive/']

In [29]:
def recall_at_10_llm(query, true_urls):
    predicted = recommend_with_llm(query)
    
    predicted_norm = set([normalize_url(u) for u in predicted])
    true_norm = set([normalize_url(u) for u in true_urls])
    
    if len(true_norm) == 0:
        return 0
    
    relevant_found = len(predicted_norm & true_norm)
    return relevant_found / len(true_norm)

In [30]:
import pandas as pd

file_path = r"C:\Users\Yekam\Downloads\Gen_AI Dataset.xlsx"

train_df = pd.read_excel(file_path, sheet_name=0)

train_grouped = train_df.groupby("Query")["Assessment_url"].apply(list).reset_index()

print("Total Queries:", len(train_grouped))

Total Queries: 10

In [31]:
def normalize_url(url):
    url = url.lower()
    url = url.replace("https://www.shl.com", "")
    url = url.replace("/solutions", "")
    url = url.rstrip("/")
    return url

In [47]:
import re

def normalize_url(url):
    url = str(url).lower()
    
    # remove domain
    url = url.replace("https://www.shl.com", "")
    
    # remove /solutions if exists
    url = url.replace("/solutions", "")
    
    # remove query parameters
    url = url.split("?")[0]
    
    # remove trailing slash
    url = url.rstrip("/")
    
    return url

In [48]:
def recall_at_10_llm(query, true_urls):
    predicted = recommend_with_llm(query)

    predicted_norm = set([normalize_url(u) for u in predicted])
    true_norm = set([normalize_url(u) for u in true_urls])

    if len(true_norm) == 0:
        return 0

    relevant_found = len(predicted_norm & true_norm)

    return relevant_found / len(true_norm)

In [49]:
query = train_grouped.iloc[0]["Query"]
true_urls = train_grouped.iloc[0]["Assessment_url"]

predicted = recommend_with_llm(query)

print("TRUE:")
for u in true_urls:
    print(normalize_url(u))

print("\nPREDICTED:")
for u in predicted:
    print(normalize_url(u))

TRUE:
/products/product-catalog/view/shl-verify-interactive-numerical-calculation
/products/product-catalog/view/administrative-professional-short-form
/products/product-catalog/view/verify-verbal-ability-next-generation
/products/product-catalog/view/occupational-personality-questionnaire-opq32r
/products/product-catalog/view/professional-7-1-solution

PREDICTED:

In [63]:
def smart_boost(query, similarities, catalog_df):
    query = query.lower()
    boosted = similarities.copy()

    for i, row in catalog_df.iterrows():
        name = str(row["name"]).lower()

        if "numerical" in query and "numerical" in name:
            boosted[i] += 0.5

        if "verbal" in query and "verbal" in name:
            boosted[i] += 0.5

        if "personality" in query and "opq" in name:
            boosted[i] += 0.6

        if "professional" in query and "professional" in name:
            boosted[i] += 0.4

        if "java" in query and "java" in name:
            boosted[i] += 0.4

        if "analysis" in query and "analysis" in name:
            boosted[i] += 0.3

    return boosted

In [64]:
def retrieve_top_10_boosted(query):
    query_clean = preprocess(query)
    query_vec = vectorizer.transform([query_clean])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()

    boosted_scores = smart_boost(query, similarities, catalog_df)

    top_indices = boosted_scores.argsort()[-10:][::-1]

    return catalog_df.iloc[top_indices]["url"].tolist()

In [65]:
def recall_at_10_boosted(query, true_urls):
    predicted = retrieve_top_10_boosted(query)

    predicted_norm = set([normalize_url(u) for u in predicted])
    true_norm = set([normalize_url(u) for u in true_urls])

    if len(true_norm) == 0:
        return 0

    return len(predicted_norm & true_norm) / len(true_norm)

In [66]:
recalls = []

for _, row in train_grouped.iterrows():
    query = row["Query"]
    true_urls = row["Assessment_url"]
    recalls.append(recall_at_10_boosted(query, true_urls))

print("Boosted Mean Recall@10:", sum(recalls)/len(recalls))

Boosted Mean Recall@10: 0.21555555555555556

In [1]:
from fastapi import FastAPI
from pydantic import BaseModel
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

app = FastAPI()

# Load catalog
catalog_df = pd.read_csv("catalog.csv")

def preprocess(text):
    text = str(text).lower()
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return text

catalog_df["clean_text"] = (
    catalog_df["name"].fillna("") + " " +
    catalog_df["url"].fillna("")
).apply(preprocess)

vectorizer = TfidfVectorizer(stop_words="english", ngram_range=(1,2))
tfidf_matrix = vectorizer.fit_transform(catalog_df["clean_text"])

def retrieve_top_10(query):
    query_clean = preprocess(query)
    query_vec = vectorizer.transform([query_clean])
    similarities = cosine_similarity(query_vec, tfidf_matrix).flatten()
    top_indices = similarities.argsort()[-10:][::-1]
    return catalog_df.iloc[top_indices]["url"].tolist()

class QueryRequest(BaseModel):
    query: str

@app.post("/recommend")
def recommend(request: QueryRequest):
    results = retrieve_top_10(request.query)
    return {"recommendations": results}

ModuleNotFoundError: No module named 'fastapi'